# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import email_backup.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.FileField(null=True, upload_to=b'')),
                ('send_by', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField(blank=True)),
                ('attaches', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('folder', models.CharField(default='/', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=64, validators=[email_backup.core.validators.host_validator])),
                ('path', models.CharField(default='/', max_length=512)),
                ('protocol', models.IntegerField(choices=[(0, 'POP3'), (1, 'IMAP4')], default=0, validators=[email_backup.core.validators.ChoicesValidator(((0, 'POP3'), (1, 'IMAP4')))])),
                ('ssl', models.BooleanField(default=True)),
                ('port', models.IntegerField(default=995, validators=[email_backup.core.validators.bind_port_validator])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='emailaccount',
            unique_together=set([('user', 'host')]),
        ),
        migrations.AddField(
            model_name='email',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EmailAccount'),
        ),
    ]
