# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import email_backup.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw', models.FileField(upload_to=b'')),
                ('message_id', models.CharField(max_length=1024)),
                ('send_by', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField(blank=True)),
                ('attaches', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('host', models.CharField(max_length=64, validators=[email_backup.core.validators.host_validator])),
                ('path', models.CharField(default='.', max_length=512, validators=[email_backup.core.validators.path_validator])),
                ('ssl', models.BooleanField(default=True)),
                ('port', models.PositiveIntegerField(default=993, validators=[email_backup.core.validators.bind_port_validator])),
                ('sync', models.BooleanField(default=False)),
                ('weeks_before', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Number of weeks until the system should process emails')),
                ('remove', models.BooleanField(default=False, help_text='Should the system remove emails when they are processed?')),
                ('just_read', models.BooleanField(default=True, help_text='Should de system ignore the unread emails?')),
            ],
        ),
        migrations.CreateModel(
            name='EmailPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2048, validators=[email_backup.core.validators.path_validator])),
                ('ignore', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ignore', to='core.EmailAccount')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='emailaccount',
            unique_together=set([('user', 'host')]),
        ),
        migrations.AddField(
            model_name='email',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.EmailAccount'),
        ),
        migrations.AddField(
            model_name='email',
            name='paths',
            field=models.ManyToManyField(related_name='emails', to='core.EmailPath'),
        ),
        migrations.AlterUniqueTogether(
            name='emailpath',
            unique_together=set([('account', 'path')]),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together=set([('account', 'message_id')]),
        ),
    ]
